name: Lint project
description: verify linting rules
runs:
  using: "composite"
  steps:
    - uses: './.github/actions/setup-environment'
    - name: Lint affected
      shell: bash
      run: npx nx affected -t lint

