name: Components tests
description: verify component tests
runs:
  using: "composite"
  steps:
    - uses: './.github/actions/setup-environment'
    - uses: './.github/actions/cypress-cache'
    - uses: './.github/actions/webpack-cache'
    - name: Test affected
      shell: bash
      run: npx nx affected -t component-test --configuration=ci

